### ISSUE TITLE
Not working on Kodi Leia 18.8.0

### ISSUE THREAD

**Issue by bosacky** [janciga/plugin.video.tv.lux.sk#1]
I am running LibreELEC 9.2.5 with Kodi version 18.8.0 on Raspberry Pi 4. The live TV throws this errror:
```
2020-10-18 11:12:58.578 T:2577630064  NOTICE: ["Initializing provider tvlux with settings {'lang': '0', 'downloads': '', 'quality': ''}"]
2020-10-18 11:12:58.679 T:2577630064   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'NoneType' object has no attribute 'group'
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.tv.lux.sk/addon.py", line 25, in <module>
                                                __addon__).run(params)
                                              File "/storage/.kodi/addons/script.module.stream.resolver/lib/contentprovider/xbmcprovider.py", line 87, in run
                                                return self.play({'url': params['play'], 'info': params})
                                              File "/storage/.kodi/addons/script.module.stream.resolver/lib/contentprovider/xbmcprovider.py", line 186, in play
                                                stream = self.resolve(item['url'])
                                              File "/storage/.kodi/addons/script.module.stream.resolver/lib/contentprovider/xbmcprovider.py", line 353, in resolve
                                                return self.provider.resolve(item, select_cb=select_cb)
                                              File "/storage/.kodi/addons/plugin.video.tv.lux.sk/resources/lib/tvlux.py", line 246, in resolve
                                                video_item['url'] = match.group('url')
                                            AttributeError: 'NoneType' object has no attribute 'group'
                                            -->End of Python script error report<--
2020-10-18 11:12:58.800 T:3011585360   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.tv.lux.sk/?play=687474703a2f2f7777772e74766c75782e736b2f6e617a69766f2f236c697665&cp=74766c7578&]
```
Playing from archive:
```
2020-10-18 11:27:51.868 T:2577630064  NOTICE: ["Initializing provider tvlux with settings {'lang': '0', 'downloads': '', 'quality': ''}"]
2020-10-18 11:27:55.058 T:3011585360  NOTICE: Previous line repeats 4 times.
2020-10-18 11:27:55.058 T:3011585360  NOTICE: VideoPlayer::OpenFile: plugin://plugin.video.tv.lux.sk/?play=68747470733a2f2f7777772e74766c75782e736b2f6172636869762f706c61792f3134373332&cp=74766c7578&
2020-10-18 11:27:55.059 T:2378163056  NOTICE: Creating InputStream
2020-10-18 11:27:55.060 T:2378163056 WARNING: CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.tv.lux.sk/?play=68747470733a2f2f7777772e74766c75782e736b2f6172636869762f706c61792f3134373332&cp=74766c7578&
2020-10-18 11:27:55.060 T:2378163056   ERROR: CVideoPlayer::OpenInputStream - error opening [plugin://plugin.video.tv.lux.sk/?play=68747470733a2f2f7777772e74766c75782e736b2f6172636869762f706c61792f3134373332&cp=74766c7578&]
2020-10-18 11:27:55.060 T:2378163056  NOTICE: CVideoPlayer::OnExit()
2020-10-18 11:27:55.109 T:2763137904   ERROR: EXCEPTION: XBMC is not playing any file
2020-10-18 11:27:55.186 T:3011585360  NOTICE: CVideoPlayer::CloseFile()
2020-10-18 11:27:55.186 T:3011585360  NOTICE: VideoPlayer: waiting for threads to exit
2020-10-18 11:27:55.186 T:3011585360  NOTICE: VideoPlayer: finished waiting
```

System configuration
```
NAME="LibreELEC"
VERSION="9.2.5"
ID="libreelec"
VERSION_ID="9.2"
PRETTY_NAME="LibreELEC (official): 9.2.5"
HOME_URL="https://libreelec.tv"
BUG_REPORT_URL="https://github.com/LibreELEC/LibreELEC.tv"
BUILD_ID="d04e8d93a2a697fe526b2ab04c495592342ca347"
OPENELEC_ARCH="RPi4.arm"
LIBREELEC_ARCH="RPi4.arm"
LIBREELEC_BUILD="official"
LIBREELEC_PROJECT="RPi"
LIBREELEC_DEVICE="RPi4"
```

**Comment by janciga** [comment]
Thank you for reporting this. I'll try to reproduce soon.

**Comment by janciga** [comment]
OK, the issue with live stream has been fixed by this PR: https://github.com/janciga/plugin.video.tv.lux.sk/pull/2
Issue with videos from archive should be fixed by this commit: https://github.com/janciga/plugin.video.tv.lux.sk/commit/4e76c7f6ad936a6631fd1c2d0f2b1047cdbfaedc
I've bumped a version so the plugin should be updated soon.

**Comment by bosacky** [comment]
It's working now. Thanks a lot
